<?php
# This file was automatically generated by the MediaWiki 1.23alpha
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

$wgLanguageCode = "ar";

require_once('LocalSettingsCommon.php');

#require_once('LocalSettingsDebug.php');
#error_reporting( E_ALL ); ini_set( 'display_errors', 1 );
#$wgShowExceptionDetails = true; 
